Company:
  defaultSize: 8
  startup-cost: 7000000
  rename-cost: 2000000
  #미납 횟수가 1 이상인 경우, 회사 유지비를 다시 1번 납부하면 미납횟수도 같이 1회가 줄어들지고 지불 가능한 미납금을 전부 납부 할지(true), 혹은 미납금을 전부 내야만 0으로 초기화 될지 (false)(충분한 가치금이 있을 경우 자동 납부 후 0)
  subtract_unPaid_times_when_pay_Fee: false
  #미납 횟수가 1 이상인 경우, 회사 유지비 납부시, 유지비 납부 후에도 0원을 초과하는 가치금이 있으면서 미납금이 있는 경우 미납금을 가치금에서 가능한 만큼 납부할지(true), 미납금을 전부 납부 가능한 금액이 있을 때만 미납금을 납부할지 (false)
  auto-pay-unPaid-fee: false

  startup-minimum-balance: 20000000
  defaultCompany-value: 5000000
  max-chars: 12
  addSize-cost:
#반드시 작은 인원에서 큰 인원 형태로 나열해야함, 20:은 20명까지를 뜻함 (20: 0~20, 30: 21~30) /
    20: 1000000.0
    30: 2500000.0
    50: 15000000.0
    max: 100000000.0
    
  maintenance_Fee_perPlayer:
#반드시 작은 인원에서 큰 인원 형태로 나열해야함, 20:은 20명까지를 뜻함 (20: 0~20, 30: 21~30) 
#조정 필요
    10: 30000.0
    15: 40000.0
    20: 50000.0
    25: 80000.0
    30: 100000.0
    40: 110000.0
    50: 115000.0
    max: 120000.0
    
  allowed_Max_Unpaid_times:
    20: 5
    30: 4
    max: 3
  

  
save-period: 180.0
companies-per-page: 15

calc-rank-period: 300.0
#회사 유지비 납부 기능 실행 간격(실행 당시 납부 대상이 아닌 회사는 납부 X)
pay-maintanFee-interval: 600.0


#단위: nD nH nM nS, 반드시 각단위는 한개만 있어야함, 또한 반드시 D H M S 의 순서여야 함
유지비납부간격: "4D 0H 0M 0S"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


#영어는 모두 소문자로
Banned-characters:
- "."
- "--"
- "/*"
- "*/"
- "##"
- "$"

confirmSec: 15
inviteSec: 30


maxSize_Company: 1000  


#예를 들어 50명에서 추가의 경우 20명,30,40명의 값들의 합을 포함할지 (예: 0~20 10만원, 20~40 20만원, 40~50 30만원, 50~ 40만원인 경우 50명 부터 는 10만+20만+30만+40만원으로 적용할지)
maxSize_sum_price: false
maintenanceFee_sum_price: false